### ISSUE TITLE
spikex download-wikigraph simplewiki_core

### ISSUE THREAD

**Issue by lbocken** [erre-quadro/spikex#9]
Hello,

I tested this command : 

`spikex download-wikigraph simplewiki_core`

In a Jupyter Notebook, it returns :  
 
`File "<ipython-input-7-d71a5d9ca149>", line 1
    spikex download-wikigraph simplewiki_core
           ^
SyntaxError: invalid syntax`

In Anaconda prompt, it returns:

`
(base) C:\WINDOWS\system32>spikex download-wikigraph simplewiki_core
Traceback (most recent call last):
  File "c:\users\ludovic\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ludovic\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ludovic\anaconda3\Scripts\spikex.exe\__main__.py", line 7, in <module>
  File "c:\users\ludovic\anaconda3\lib\site-packages\spikex\__main__.py", line 23, in main
    typer.run(commands[command])
  File "c:\users\ludovic\anaconda3\lib\site-packages\typer\main.py", line 859, in run
    app()
  File "c:\users\ludovic\anaconda3\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "c:\users\ludovic\anaconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ludovic\anaconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\ludovic\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ludovic\anaconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ludovic\anaconda3\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "c:\users\ludovic\anaconda3\lib\site-packages\spikex\cli\download.py", line 46, in download_wikigraph
    _run_command(f"wget --quiet --show-progress -O {wg_tar} {wg_url}")
  File "c:\users\ludovic\anaconda3\lib\site-packages\spikex\cli\download.py", line 54, in _run_command
    return run(
  File "c:\users\ludovic\anaconda3\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\ludovic\anaconda3\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\ludovic\anaconda3\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

(base) C:\WINDOWS\system32>`

What can I do ? 

Thank you very much for your help !

**Comment by fnielsen** [comment]
On the main page it says "Windows not supported yet". So I guess you either have to wait, fix it or change operating system to Linux or macOS. The program uses `wget`. I wonder if you have installed that? Installing that will perhaps get you a bit futher. 

In Jupyter Notebook, you probably need and exclamation mark. `!spikex download-wikigraph simplewiki_core`, before you get the same error as the Anaconda prompt.
